#!/usr/bin/env node

"use strict"

var context = require("commander");

context
    .command("create [OPTIONS]", "Create one user")
    .command("remove [OPTIONS]", "Remove one user")
    .command("verify [OPTIONS]", "Verify user credentials")
    .command("confirm [OPTIONS]", "Confirm user signup")
    .parse(process.argv);
